### ISSUE TITLE
Drapeau

### ISSUE THREAD

**Issue by lebarbare** [Xen0Xys/Coop-Demineur#1]
quand un drapeau est mis sur une case et que l on clique sure une case vide a cotee et que le drapeau est sur une case qui se revele (tout sauf mine) le drapeau disparait et ne reviens pas au conteur

**Comment by lebarbare** [comment]
quand on clique sur le nombre de drapeau restant le chiffres du temps ou le mot temps cela considere un clique sur la case du coin haut gauche

**Comment by Xen0Xys** [comment]
Issue Fixed.
